### ISSUE TITLE
Add permalinks for tracks

### ISSUE THREAD

**Issue by bryansum** [jescriba/music-archive-sinatra#9]
Since tracks can be cross-listed, might make sense to do something like: `/_person_/:track`or similar? Or I guess you could make it a `/_person_/#track` slug and leave it up to the JS client to handle the track playback.

**Comment by jescriba** [comment]
I ended up just adding a share button that opens a prompt to copy the direct link as `/song/:id`. Maybe something that could be improved later but suffices for now.
